### ISSUE TITLE
Feature Request: Add ability to configure Gubernator using command-line flags

### ISSUE THREAD

**Issue by kakkoyun** [mailgun/gubernator#73]
It would be nice to have the ability to configure the Gubernator using flags in addition to environment variables. 
Using flags makes configuration explicit and immutable which is preferable for more reliable rollouts.

Is there a chance to consider this? 

cc @thrawn01

**Comment by thrawn01** [comment]
I'm wondering if command line arguments will be worth the additional effort involved.

It's currently possible to make configuration explicit by putting the environment variables in a config file and passing it with `-config`. Most docker orchestration systems prefer ENV configuration which is why I choose this as the primary config path. (See the `docker-compose.yaml` and `k8s-deployment.yaml`) It's also the recommended config method in the [12 factor app](https://12factor.net/config)  manifesto.

Could you please explain your use case?

**Comment by kakkoyun** [comment]
I'd be happy to elaborate.  The command-line arguments are a self-documenting way to describe the configuration of your program at runtime. It's much easier than trying to find out a set of relevant environment variables in the documentation or figure out the syntax and valid key names of a config file format. If running a program with the `-h` flag provides a complete list of the configuration that controls its behaviour, then it’s very easy for an on-call engineer to adjust something during an incident, or for a new engineer to get it running in their dev environment. 

Also, the command-line flags are immutable so that you know how your program will behave for the whole life-cycle of your program. You don't have to worry about whether you have to restart your program if you change an environment variable or a configuration file. This improves the predictability and reliability of the runtime behaviour of a program.

It shouldn't take too much effort to add those in addition to the environment variables and configuration files. There are really helpful libraries that can provide all three functionality with the help of a single interface.

All that being said, I'd be more than happy to contribute to your project to add this functionality. Tell me if you have any preferences or requirements for a new contributor so that I can get to it right away.
