### ISSUE TITLE
Date to release 1.0 final

### ISSUE THREAD

**Issue by matheus-meneses** [mailgun/gubernator#88]
Hello guys, 

Do you have a date to release 1.0 final version?

**Comment by thrawn01** [comment]
We have been super busy and have not had enough time to dedicate to the final performance review or completion of multi-region support. If you are interested in helping with either it would be most appreciated. Also, the release candidates are available for use until we get the final changes in for the 1.0 release. I keep the docker containers update with each release.

### Items todo
1. This hack needs to implemented properly https://github.com/mailgun/gubernator/issues/74#issuecomment-768471645 in a nut shell we need to avoid spawning a go routine if we know the local instance owns the ratelimit.
2. We need some automated tests to exercise mulit-region support, most of the pieces are coded for this to work, we just need to setup 2 clusters with a mutli-region config and see if it works and fill in what is missing. (If anything)

**Comment by thrawn01** [comment]
Because of protobuf issues we have bumped the release to 2.0 release candidate to avoid go mod issue when importing gubernator into other projects that use protobuf. Multi-Region support is still a goal for 2.0, but please feel free to use the release candidates until I or someone else has time to finish testing.
